import 'package:flutter/material.dart';
import 'package:random_color/random_color.dart';
import 'package:http/http.dart' as http;
import 'package:todo_app/utils/app_constants.dart';
import 'dart:convert';

import 'package:todo_app/utils/unitily.dart';

/// This class is provider of the single todo item
///
/// This class contains the logic for mark a todo item completed.
class TodoItem with ChangeNotifier {
  /// title of todo item
  final String title;

  /// creation time of todo item
  String time;

  /// id of todo item, autogenerated
  final String id;

  /// determines the completion state of todo item
  bool isCompleted;

  /// getter for random color used in gradient background
  Color get randomColor {
    RandomColor _randomColor = RandomColor();
    return _randomColor.randomColor(colorHue: ColorHue.random);
  }

  /// Constructor
  TodoItem({
    @required this.id,
    this.time = '',
    @required this.title,
    this.isCompleted = false,
  });

  /// This method is to mark the todo item completed.
  Future<void> markCompleted() async {
    final isInternetConnected = await Util.checkInternet();
    if (!isInternetConnected) {
      notifyListeners();
      throw Exception(INTERNET_NOT_CONNECTED);
    }
    isCompleted = true;
    notifyListeners();
    final url = CREATE_TASK_URL + '/${id}';
    final _ = await http.patch(
      url,
      body: json.encode(
        {
          'completed': true,
        },
      ),
      headers: HEADERS,
    );
  }
}
